vagrant-centos7:
  ssh_options:
    user: vagrant
    host_name: 127.0.0.1
    port: 2222
    keys: .vagrant/machines/default/virtualbox/private_key
  properties:
    preferred_driver: mitamae
    # sudo_required: false
    nopasswd_sudo: true
    run_list:
      - roles/default.rb
