docker-ubuntu:
  ssh_options:
    user: root
    host_name: localhost
    port: 2222
    auth_methods: [password]
    password: pass
    # passwordauthentication
  properties:
    # preferred_driver: bundler
    preferred_driver: mitamae
    # attributes:
    #   node_attributes_goes_here: hello
    run_list:
      - roles/default.rb

vagrant-centos7:
  ssh_options:
    user: vagrant
    host_name: 127.0.0.1
    port: 2222
    keys: .vagrant/machines/default/virtualbox/private_key
  properties:
    preferred_driver: mitamae
    # sudo_required: false
    nopasswd_sudo: true
    run_list:
      - roles/default.rb
