docker-ubuntu:
  ssh_options:
    user: root
    host_name: localhost
    port: 2222
    auth_methods: [password]
    password: pass
    # passwordauthentication
  properties:
    # preferred_driver: bundler
    preferred_driver: mitamae
    # attributes:
    #   node_attributes_goes_here: hello
    run_list:
      - roles/default.rb
